name: test
on:
  push:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: git config user
        uses: fregante/setup-git-user@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
    
      - run: |
          chmod +x script.sh
          ./script.sh
        
      - env:
          COOKIE: ${{ secrets.COOKIE }}
        run:  
          python main.py "$COOKIE"
      

      - name: 포스팅 commit
        run: |
          git add posts
          if [[ $(git diff --name-only --cached) ]]; then
            git commit -m "add post: $(echo $(git diff --name-only --cached))"
            git log
          fi
          