name: test
on:
  push:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: git config user
        uses: fregante/setup-git-user@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
     
      - env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          chmod +x script.sh
          ./script.sh "$COOKIE"